config/routes.rb
Rails.application.routes.draw do
  resources :stores
  root 'stores#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #get '/stores', to: 'stores#index'
  #get '/stores/new', to: 'stores#new'
  #post '/stores', to: 'stores#create'
  #get '/stores/:id/edit', to: 'stores#edit', as: 'edit_store'
  #patch '/stores/:id', to: 'stores#update'
  #delete '/store/:id', to: 'stores#delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/store.rb
class Store < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  before_action :set_store, only: [:show, :edit, :update, :destroy]

  def index
    @stores = Store.all
  end

  def show

  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to stores_path
    else
      render :new
    end

  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    if @store.update(store_params)
      redirect_to stores_path
    else
      render :edit
    end
  end

  def destroy
      @store = Store.find(params[:id])
      @store.destroy
      respond_to do |format|
        format.html { redirect_to stores_url, notice: 'Person was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

  private

  def set_store
      @store = Store.find(params[:id])
    end

  def store_params
    params.require(:store).permit(:cod, :nombre, :proveedor)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="menu">CRUD Ruby On Rails</div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stores/edit.html.erb
<div class="for_edit">
    <%= form_for @store do |f| %>
      <div>
        <%= f.label :Código %>
        <%= f.number_field :cod %>
      </div>
      <div>
        <%= f.label :Nombre %>
        <%= f.text_field :nombre %>
      </div>
      <div>
        <%= f.label :Proveedor %>
        <%= f.text_field :proveedor %>
      </div>
      <div>
        <%= f.submit %>
        |
        <%= fa_icon "reply-all" %>
        <%= link_to 'Atras', stores_path %>
      </div>
    <% end %>
</div>

app/views/stores/index.html.erb
<h1>
  <%= fa_icon "list" %>
  Lista de Productos
</h1>

<%= fa_icon "plus-circle" %>
<%= link_to 'Nuevo Producto', new_store_path %>

<table class="table">
  <tr>
    <thead class="thead-dark">
      <th>
        <%= fa_icon "code" %>
        Código
      </th>
      <th>
        <%= fa_icon "file" %>
        Nombre
      </th>
      <th>
        <%= fa_icon "cubes" %>
        Proveedor
      </th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
  </tr>
  <% @stores.each do |store| %>
  <tr>
      <td><%= store.cod %></td>
      <td><%= store.nombre %></td>
      <td><%= store.proveedor %></td>


      <td>
      <%= fa_icon "pencil" %>
      <%= link_to "Editar", edit_store_path(store)%>
      </td>
      <td>
        <%= fa_icon "times" %>
        <%= link_to "Eliminar",store, method: :delete, data: { confirm: '¿Desea borrar este articulo?' } %>
      </td>
      <td>
        <%= fa_icon "eye" %>
        <%= link_to "Mostrar", store %>
      </td>

  </tr>
  <% end %>
</table>

app/views/stores/new.html.erb
<%= form_for @store do |f| %>
  <div>
    <%= f.label :Código %>
    <%= f.number_field :cod %>
  </div>
  <div>
    <%= f.label :Nombre %>
    <%= f.text_field :nombre %>
  </div>
  <div>
    <%= f.label :Proveedor %>
    <%= f.text_field :proveedor %>
  </div>
  <div>
    <%= f.submit %> |
    <%= fa_icon "reply-all" %>
    <%= link_to 'Atras', stores_path %>
  </div>
<% end %>

app/views/stores/show.html.erb
<div>
    <p>
      <strong>Código:</strong>
      <%= @store.cod %>
    </p>

    <p>
      <strong>Nombre:</strong>
      <%= @store.nombre %>
    </p>

    <p>
      <strong>proveedor:</strong>
      <%= @store.proveedor %>
    </p>

    <%= fa_icon "pencil" %>
    <%= link_to 'Edit', edit_store_path(@store) %> |
    <%= fa_icon "reply-all" %>
    <%= link_to 'Back', stores_path %>
</div>